[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.0.0-rc15"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[[constraint]]
  branch = "master"
  name = "github.com/bramvdbogaerde/go-scp"
