[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"
